import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./customer/context/contextCart";
import { AccountProvider } from "./customer/context/contextAccount";
import { CategoryProvider } from "./customer/context/contextCategory";
import { ProductProvider } from "./customer/context/contextProduct";
import { BannerProvider } from "./customer/context/contextBanner";
import { NotificationProvider } from "./customer/context/contextNotification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Outermost: Knows WHO the user is */}
        <AccountProvider>
          {/* Middle: User-specific features (Cart & Notifications) */}
          <NotificationProvider>
            <CartProvider>
              {/* Innermost: Global App Data (Products, Categories, Banners) */}
              <CategoryProvider>
                <ProductProvider>
                  <BannerProvider>
                    {/* Your Pages */}
                    {children}
                  </BannerProvider>
                </ProductProvider>
              </CategoryProvider>
            </CartProvider>
          </NotificationProvider>
        </AccountProvider>
      </body>
    </html>
  );
}
