from app.src.exceptions.domain_exceptions import (DomainAlreadyExistsError, DomainDeactivatedError,
                                                  DomainEntityStatusInvalidError, DomainError,
                                                  DomainForbiddenAccessError, DomainInvalidCredentialsError,
                                                  DomainInvalidSignInType,
                                                  DomainJWTExpiredError,
                                                  DomainJWTInvalidError, DomainMaximumDataExceed,
                                                  DomainNotActivatedError, DomainNotFoundError,
                                                  DomainOTPExpiredError, DomainOTPInvalidError, DomainOTPNotExpireError,
                                                  DomainUnprocessableEntityError, )
from app.src.exceptions.http_exceptions import (DataBadRequestException, DataBaseDataNotFoundException,
                                                DataConflictError, DataForbiddenException,
                                                DataUnProcessableContent, JWTExpiredException, JWTInvalidException,
                                                UnAuthorizeAccessException, )

EXCEPTION_MAPPER = {
        DomainNotFoundError           : lambda e: DataBaseDataNotFoundException('Entity not found', message=str(e)),
        DomainAlreadyExistsError      : lambda e: DataConflictError('Entity already exists', message=str(e)),
        DomainOTPNotExpireError       : lambda e: DataBadRequestException("OTP not expired", message=str(e)),
        DomainDeactivatedError        : lambda e: DataBadRequestException('Account deactivated', message=str(e)),
        DomainOTPInvalidError         : lambda e: DataBadRequestException('Invalid OTP', message=str(e)),
        DomainOTPExpiredError         : lambda e: DataBadRequestException(message_status='OTP Expired', message=str(e)),
        DomainMaximumDataExceed       : lambda e: DataBadRequestException(message_status='Maximum Exceed',
                                                                          message=str(e)),
        DomainEntityStatusInvalidError: lambda e: DataBadRequestException(message_status='Invalid Status',
                                                                          message=str(e)),
        DomainForbiddenAccessError    : lambda e: DataForbiddenException(message_status='Invalid Status',
                                                                         message=str(e)),
        DomainInvalidCredentialsError : lambda e: DataBadRequestException(message_status='Invalid Credentials',
                                                                          message=str(e)),
        DomainNotActivatedError       : lambda e: DataForbiddenException(message_status='Account not verified',
                                                                         message=str(e)),
        DomainInvalidSignInType       : lambda e: DataBadRequestException(message_status='Invalid Sign-in type',
                                                                          message=str(e)),
        DomainUnprocessableEntityError: lambda e: DataUnProcessableContent(message_status='Unprocessable Entity',
                                                                           message=str(e)),
        DomainError                   : lambda e: DataBadRequestException(message_status='Domain error',
                                                                          status_code=500,
                                                                          message=str(e)),
        DomainJWTInvalidError         : lambda e: JWTInvalidException(message_status='Invalid Token', message=str(e)),
        DomainJWTExpiredError         : lambda e: JWTExpiredException(message_status='Expired Token', message=str(e)),
        }
