"""orders

Revision ID: 051e925f72cc
Revises: 
Create Date: 2026-03-01 20:31:59.144873

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '051e925f72cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

order_status_enum = sa.Enum('Pending', 'Approved', 'Shipped', 'Delivered', 'Cancelled', 'Returned',
                            name='order_status_enum')
order_payment_status_enum = sa.Enum('Unpaid', 'Paid', 'Failed', 'Refunded', name='payment_status_enum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    order_payment_status_enum.create(bind, checkfirst=True)
    order_status_enum.create(bind, checkfirst=True)
    op.add_column('orders', sa.Column('order_status', order_status_enum, nullable=False))
    op.add_column('orders',
                  sa.Column('payment_status', order_payment_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
