"""add index for transaction num

Revision ID: 07486a6af755
Revises: c7b0fb4c3617
Create Date: 2026-03-12 13:18:44.508138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07486a6af755'
down_revision: Union[str, Sequence[str], None] = 'c7b0fb4c3617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_transaction_reference_key'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.create_unique_constraint(op.f('transactions_transaction_reference_key'), 'transactions', ['transaction_reference'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
