"""id

Revision ID: 0a19b0377921
Revises: 1ae7ed2b337c
Create Date: 2026-03-12 14:48:03.347434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0a19b0377921'
down_revision: Union[str, Sequence[str], None] = '1ae7ed2b337c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('string_id', sa.String(), nullable=False))
    op.alter_column('orders', 'id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    postgresql_using='id::integer',
                    existing_nullable=False,
                    existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.create_unique_constraint(None, 'orders', ['string_id'])
    op.alter_column('transactions', 'order_id',
                    existing_type=sa.VARCHAR(),
                    postgresql_using='order_id::integer',
                    type_=sa.Integer(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'order_id',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'id',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False,
                    existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.drop_column('orders', 'string_id')
    # ### end Alembic commands ###
