"""update

Revision ID: 26c4bfd74e69
Revises: 8d252ad80a09
Create Date: 2026-03-08 13:26:21.896192

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26c4bfd74e69'
down_revision: Union[str, Sequence[str], None] = '8d252ad80a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'total')
    op.add_column('transactions', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('payment_status',
                                            sa.Enum('Unpaid', 'Paid', 'Failed', 'Refunded', name='payment_status_enum'),
                                            nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.Enum('COD', 'G_CASH', 'CREDIT_CARD', 'DEBIT_CARD',
                                                                      name='order_payment_method'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'payment_status')
    op.drop_column('transactions', 'total_amount')
    op.add_column('orders', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('payment_method', postgresql.ENUM('COD', 'G_CASH', 'CREDIT_CARD', 'DEBIT_CARD',
                                                                        name='order_payment_method'),
                                      autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('payment_status', postgresql.ENUM('Unpaid', 'Paid', 'Failed', 'Refunded',
                                                                        name='payment_status_enum'),
                                      autoincrement=False, nullable=False))
    # ### end Alembic commands ###
