"""added transactions

Revision ID: 8d252ad80a09
Revises: e864cacb59bf
Create Date: 2026-03-07 15:08:55.662044

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d252ad80a09'
down_revision: Union[str, Sequence[str], None] = 'e864cacb59bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('transaction_reference', sa.String(), nullable=False),
                    sa.Column('payment_provider_reference', sa.String(), nullable=True),
                    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='Cascade'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('payment_provider_reference'),
                    sa.UniqueConstraint('transaction_reference')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
