"""remove status on

Revision ID: e864cacb59bf
Revises: 051e925f72cc
Create Date: 2026-03-06 05:38:56.028227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e864cacb59bf'
down_revision: Union[str, Sequence[str], None] = '051e925f72cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'available_stock')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('available_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
